In [1]:
import pandas as pd
from datetime import date, datetime

import matplotlib.pyplot as plt
import numpy as np
import statsmodels.api as sm

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_rows',50)
pd.set_option('display.max_columns',50)
pd.set_option('display.width',100)

In [2]:
df = pd.read_csv(r'/Users/lingchen/Documents/DSI/WEEK 8/new_retail_data.csv')
# Select columns I need
df = df[['Transaction_ID','Customer_ID','City', 'State','Country', 'Age', 'Gender', 'Income',
       'Customer_Segment', 'Date', 'Year', 'Month', 'Time', 'Total_Purchases',
       'Amount', 'Total_Amount', 'Product_Category', 'Product_Brand',
       'Product_Type', 'Feedback', 'Shipping_Method', 'Payment_Method',
       'Order_Status', 'Ratings', 'products']]
df.shape# Drop null rows

(302010, 25)

In [3]:
df_cleaned = df.dropna()
df_cleaned.shape

(295617, 25)

In [4]:
# Data type conversions
df_cleaned['Date'] = pd.to_datetime(df_cleaned['Date'], format='%m/%d/%Y')
# Create a new column to store yearmonth as integer
df_cleaned['yearmonth'] = df_cleaned['Date'].dt.strftime('%Y%m').astype(int)

df_cleaned

,Transaction_ID,Customer_ID,City,State,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products,yearmonth
0,8691788.0,37249.0,Dortmund,Berlin,Germany,21.0,Male,Low,Regular,2023-09-18,2023.0,September,22:03:55,3.0,108.028757,324.086270,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts,202309
1,2174773.0,69749.0,Nottingham,England,UK,19.0,Female,Low,Premium,2023-12-31,2023.0,December,8:42:04,2.0,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab,202312
2,6679610.0,30192.0,Geelong,New South Wales,Australia,48.0,Male,Low,Regular,2023-04-26,2023.0,April,4:06:29,3.0,354.477600,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment,202304
3,7232460.0,62101.0,Edmonton,Ontario,Canada,56.0,Male,High,Premium,2023-05-08,2023.0,May,14:55:17,7.0,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife,202305
4,4983775.0,27901.0,Bristol,England,UK,22.0,Male,Low,Premium,2024-01-10,2024.0,January,16:54:07,2.0,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies,202401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302005,4246475.0,12104.0,Townsville,New South Wales,Australia,31.0,Male,Medium,Regular,2024-01-20,2024.0,January,23:40:29,5.0,194.792597,973.962984,Books,Penguin Books,Fiction,Bad,Same-Day,Cash,Processing,1.0,Historical fiction,202401
302006,1197603.0,69772.0,Hanover,Berlin,Germany,35.0,Female,Low,New,2023-12-28,2023.0,December,2:55:45,1.0,285.137301,285.137301,Electronics,Apple,Laptop,Excellent,Same-Day,Cash,Processing,5.0,LG Gram,202312
302007,7743242.0,28449.0,Brighton,England,UK,41.0,Male,Low,Premium,2024-02-27,2024.0,February,2:43:49,3.0,60.701761,182.105285,Clothing,Adidas,Jacket,Average,Express,Cash,Shipped,2.0,Parka,202402
302008,9301950.0,45477.0,Halifax,Ontario,Canada,41.0,Male,Medium,New,2023-09-03,2023.0,September,11:20:31,1.0,120.834784,120.834784,Home Decor,IKEA,Furniture,Good,Standard,Cash,Shipped,4.0,TV stand,202309
302009,2882826.0,53626.0,Tucson,West Virginia,USA,28.0,Female,Low,Premium,2024-01-08,2024.0,January,11:44:36,7.0,340.319059,2382.233417,Home Decor,Home Depot,Decorations,Average,Same-Day,Cash,Shipped,2.0,Clocks,202401

### Linear Regression Model

1. Overall transaction value by country

In [5]:
import pandas as pd
import statsmodels.api as sm

df_cleaned_1 = df_cleaned[['Country', 'Total_Amount']]
df_cleaned_1 = df_cleaned_1.dropna()


X = pd.get_dummies(df_cleaned_1[['Country']], drop_first=False)
y = df_cleaned_1['Total_Amount']

X = X.astype(float)
y = y.astype(float)

# Add constant to X
X = sm.add_constant(X)

model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           Total_Amount   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.7587
Date:                Sat, 22 Jun 2024   Prob (F-statistic):              0.552
Time:                        00:27:54   Log-Likelihood:            -2.4973e+06
No. Observations:              295617   AIC:                         4.995e+06
Df Residuals:                  295612   BIC:                         4.995e+06
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const             -3.956e+14   7.44e+14     -0.532      0.595   -1.85e+15    1.06e+15
Country_Australia  3.956e+14   7.44e+14      0.532      0.595   -1.06e+15    1.85e+15
Country_Canada     3.956e+14   7.44e+14      0.532      0.595   -1.06e+15    1.85e+15
Country_Germany    3.956e+14   7.44e+14      0.532      0.595   -1.06e+15    1.85e+15
Country_UK         3.956e+14   7.44e+14      0.532      0.595   -1.06e+15    1.85e+15
Country_USA        3.956e+14   7.44e+14      0.532      0.595   -1.06e+15    1.85e+15
==============================================================================
Omnibus:                    33870.038   Durbin-Watson:                   2.005
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            47019.288
Skew:                           0.973   Prob(JB):                         0.00
Kurtosis:                       3.176   Cond. No.                     9.71e+14
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.83e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

2. Overall transaction value by income

In [6]:
import pandas as pd
import statsmodels.api as sm

df_cleaned = df_cleaned.dropna()


df_cleaned_2 = df_cleaned[['Income', 'Total_Amount']]
df_cleaned_2 = df_cleaned_2.dropna()

X = pd.get_dummies(df_cleaned_2['Income'], drop_first=False)
y = df_cleaned_2['Total_Amount']

X = X.astype(float)
y = y.astype(float)

# Add constant to X
X = sm.add_constant(X)

model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           Total_Amount   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     1.065
Date:                Sat, 22 Jun 2024   Prob (F-statistic):              0.363
Time:                        00:28:00   Log-Likelihood:            -2.4973e+06
No. Observations:              295617   AIC:                         4.995e+06
Df Residuals:                  295613   BIC:                         4.995e+06
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.166e+14   3.84e+14      1.084      0.278   -3.37e+14    1.17e+15
High       -4.166e+14   3.84e+14     -1.084      0.278   -1.17e+15    3.37e+14
Low        -4.166e+14   3.84e+14     -1.084      0.278   -1.17e+15    3.37e+14
Medium     -4.166e+14   3.84e+14     -1.084      0.278   -1.17e+15    3.37e+14
==============================================================================
Omnibus:                    33870.986   Durbin-Watson:                   2.005
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            47020.971
Skew:                           0.973   Prob(JB):                         0.00
Kurtosis:                       3.176   Cond. No.                     4.31e+14
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.16e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

As all P-value is extremly large, we can know that 'Income' is not statistically sigficiant to purchase amount, which means the income level is not asscoiated with sales.