In [2]:
import pandas as pd

#upload data 
df = pd.read_csv(r'C:/Users/kgogi/DSI/team_project/data/new_retail_data.csv')

print(df.head())

   Transaction_ID  Customer_ID                 Name                Email  \
0       8691788.0      37249.0  Michelle Harrington    Ebony39@gmail.com
1       2174773.0      69749.0          Kelsey Hill     Mark36@gmail.com
2       6679610.0      30192.0         Scott Jensen    Shane85@gmail.com
3       7232460.0      62101.0        Joseph Miller     Mary34@gmail.com
4       4983775.0      27901.0        Debra Coleman  Charles30@gmail.com

          Phone                      Address        City            State  \
0  1.414787e+09            3959 Amanda Burgs    Dortmund           Berlin
1  6.852900e+09           82072 Dawn Centers  Nottingham          England
2  8.362160e+09            4133 Young Canyon     Geelong  New South Wales
3  2.776752e+09  8148 Thomas Creek Suite 100    Edmonton          Ontario
4  9.098268e+09    5813 Lori Ports Suite 269     Bristol          England

   Zipcode    Country  ...  Total_Amount Product_Category  Product_Brand  \
0  77985.0    Germany  ...    324.086270         Clothing           Nike
1  99071.0         UK  ...    806.707815      Electronics        Samsung
2  75929.0  Australia  ...   1063.432799            Books  Penguin Books
3  88420.0     Canada  ...   2466.854021       Home Decor     Home Depot
4  48704.0         UK  ...    248.553049          Grocery         Nestle

  Product_Type   Feedback  Shipping_Method Payment_Method Order_Status  \
0       Shorts  Excellent         Same-Day     Debit Card      Shipped
1       Tablet  Excellent         Standard    Credit Card   Processing
2   Children's    Average         Same-Day    Credit Card   Processing
3        Tools  Excellent         Standard         PayPal   Processing
4    Chocolate        Bad         Standard           Cash      Shipped

   Ratings           products
0      5.0     Cycling shorts
1      4.0         Lenovo Tab
2      2.0   Sports equipment
3      4.0      Utility knife
4      1.0  Chocolate cookies

[5 rows x 30 columns]

(302010, 30)

In [14]:
print("Data types of all columns before conversion:")
print(df.dtypes)
print("\nSummary of the DataFrame:")
df.info()

Data types of all columns before conversion:
yearmonth    int64
dtype: object

Summary of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   yearmonth  4 non-null      int64
dtypes: int64(1)
memory usage: 160.0 bytes

In [4]:
# checking the amount of the cell and row
df.shape

(302010, 30)

Data cleaning

In [5]:
# Drop null rows
df_cleaned = df.dropna()
df_cleaned.shape

(293911, 30)

In [7]:
# Data type conversions
df_cleaned['Date'] = pd.to_datetime(df_cleaned['Date'], format='%m/%d/%Y')
# Create a new column to store yearmonth as integer
df_cleaned['yearmonth'] = df_cleaned['Date'].dt.strftime('%Y%m').astype(int)

df_cleaned

C:\Users\kgogi\AppData\Local\Temp\ipykernel_8980\3698922614.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Date'] = pd.to_datetime(df_cleaned['Date'], format='%m/%d/%Y')
C:\Users\kgogi\AppData\Local\Temp\ipykernel_8980\3698922614.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['yearmonth'] = df_cleaned['Date'].dt.strftime('%Y%m').astype(int)

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,...,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products,yearmonth
0,8691788.0,37249.0,Michelle Harrington,Ebony39@gmail.com,1.414787e+09,3959 Amanda Burgs,Dortmund,Berlin,77985.0,Germany,...,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts,202309
1,2174773.0,69749.0,Kelsey Hill,Mark36@gmail.com,6.852900e+09,82072 Dawn Centers,Nottingham,England,99071.0,UK,...,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab,202312
2,6679610.0,30192.0,Scott Jensen,Shane85@gmail.com,8.362160e+09,4133 Young Canyon,Geelong,New South Wales,75929.0,Australia,...,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment,202304
3,7232460.0,62101.0,Joseph Miller,Mary34@gmail.com,2.776752e+09,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420.0,Canada,...,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife,202305
4,4983775.0,27901.0,Debra Coleman,Charles30@gmail.com,9.098268e+09,5813 Lori Ports Suite 269,Bristol,England,48704.0,UK,...,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies,202401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302005,4246475.0,12104.0,Meagan Ellis,Courtney60@gmail.com,7.466354e+09,389 Todd Path Apt. 159,Townsville,New South Wales,4567.0,Australia,...,Books,Penguin Books,Fiction,Bad,Same-Day,Cash,Processing,1.0,Historical fiction,202401
302006,1197603.0,69772.0,Mathew Beck,Jennifer71@gmail.com,5.754305e+09,52809 Mark Forges,Hanover,Berlin,16852.0,Germany,...,Electronics,Apple,Laptop,Excellent,Same-Day,Cash,Processing,5.0,LG Gram,202312
302007,7743242.0,28449.0,Daniel Lee,Christopher100@gmail.com,9.382530e+09,407 Aaron Crossing Suite 495,Brighton,England,88038.0,UK,...,Clothing,Adidas,Jacket,Average,Express,Cash,Shipped,2.0,Parka,202402
302008,9301950.0,45477.0,Patrick Wilson,Rebecca65@gmail.com,9.373222e+09,3204 Baird Port,Halifax,Ontario,67608.0,Canada,...,Home Decor,IKEA,Furniture,Good,Standard,Cash,Shipped,4.0,TV stand,202309
302009,2882826.0,53626.0,Dustin Merritt,William14@gmail.com,9.518927e+09,143 Amanda Crescent,Tucson,West Virginia,25242.0,USA,...,Home Decor,Home Depot,Decorations,Average,Same-Day,Cash,Shipped,2.0,Clocks,202401

Linear Regression Model

In [6]:
import statsmodels.api as sm
X = df_cleaned[['Age','Ratings']]
y = df_cleaned['Total_Amount']

# Add constant to X
X = sm.add_constant(X)

model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           Total_Amount   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     82.60
Date:                Thu, 20 Jun 2024   Prob (F-statistic):           1.38e-36
Time:                        10:12:07   Log-Likelihood:            -2.4829e+06
No. Observations:              293911   AIC:                         4.966e+06
Df Residuals:                  293908   BIC:                         4.966e+06
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1324.8376      6.806    194.655      0.000    1311.498    1338.177
Age            1.7860      0.141     12.703      0.000       1.510       2.062
Ratings       -6.4806      1.599     -4.054      0.000      -9.614      -3.347
==============================================================================
Omnibus:                    33647.061   Durbin-Watson:                   2.005
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            46696.661
Skew:                           0.972   Prob(JB):                         0.00
Kurtosis:                       3.176   Cond. No.                         128.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [15]:
import statsmodels.api as sm
X = df_cleaned['Age']
y = df_cleaned['Ratings']

# Add constant to X
X = sm.add_constant(X)

model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                Ratings   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.028
Method:                 Least Squares   F-statistic:                     8462.
Date:                Thu, 20 Jun 2024   Prob (F-statistic):               0.00
Time:                        10:21:45   Log-Likelihood:            -4.9464e+05
No. Observations:              293911   AIC:                         9.893e+05
Df Residuals:                  293909   BIC:                         9.893e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.6405      0.006    428.665      0.000       2.628       2.653
Age            0.0147      0.000     91.987      0.000       0.014       0.015
==============================================================================
Omnibus:                   137336.310   Durbin-Watson:                   1.432
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            17880.846
Skew:                          -0.232   Prob(JB):                         0.00
Kurtosis:                       1.884   Cond. No.                         98.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.